### ISSUE TITLE
Briefly shows login form before proceeding to timeline

### ISSUE THREAD

**Issue by gahbla** [pixelfed/pixelfed-rn#8]
Whenever I open the app, it briefly shows the login screen although I'm already logged in. It then quickly proceeds to load the timeline.

https://github.com/pixelfed/pixelfed-rn/assets/121877105/79039976-965a-48f4-b33e-5b92f14917ad

**Comment by dansup** [comment]
Fixed in latest commits!

**Comment by ftgjhf** [comment]
I can still reproduce this, especially after restarting my phone (but sometimes even without that). Tested on the latest iOS version of the app on iOS 18.4.
