### ISSUE TITLE
View more for caption text 

### ISSUE THREAD

**Issue by blueberrie231** [pixelfed/pixelfed-rn#84]
Some of the post caption text is not visible and there is not a "view more" option. It's a bit cumbersome to go onto view post to read the whole text.

![Screenshot_2024-07-09-22-00-37-14_04d1a00dc423a8847c8d557f42f6d70c.jpg](https://github.com/pixelfed/pixelfed-rn/assets/170041854/2f87fc73-cfec-4139-997c-34b8ec58bbfd)

**Comment by dansup** [comment]
This has been fixed in v1.0.0.65!

**Comment by earth-walker** [comment]
I'm still seeing this behavior in 1.0.0.65. It shows an ellipsis (...) Rather than a "show more" button in feed view when the caption is too long.

![Screenshot_20240717-103346_pixelfed](https://github.com/user-attachments/assets/84a90ff7-bccd-43a3-a342-97c87e774562)

![Screenshot_20240717-103133_pixelfed](https://github.com/user-attachments/assets/d2c71b58-c3ba-47f9-9003-9820715fd8be)
